export const COMMANDS = [
  { id: "fwd", label: "Avanzar", glyph: "▲" },
  { id: "left", label: "Girar izq.", glyph: "↶" },
  { id: "right", label: "Girar der.", glyph: "↷" },
  { id: "jump", label: "Saltar", glyph: "⤒" },
  { id: "light", label: "Luz", glyph: "✦" },
  { id: "p1", label: "Proc. 1", glyph: "P1" },
  { id: "p2", label: "Proc. 2", glyph: "P2" },
];

const ALL = COMMANDS.map((c) => c.id);

function L(partial) {
  return {
    slots: { main: 12, p1: 8, p2: 8 },
    allowed: ALL,
    ...partial,
  };
}

export const CAMPAIGN = [
  L({
    id: "c01",
    name: "Primera chispa",
    hint: "Avanza hasta la baldosa marcada y enciende la lámpara.",
    width: 4,
    depth: 3,
    cells: [
      { x: 0, y: 1, z: 1 },
      { x: 1, y: 1, z: 1 },
      { x: 2, y: 1, z: 1, lamp: true },
    ],
    start: { x: 0, y: 1, dir: 0 },
    allowed: ["fwd", "light"],
    slots: { main: 6, p1: 0, p2: 0 },
  }),
  L({
    id: "c02",
    name: "La esquina",
    hint: "Gira a la derecha y luego avanza hacia la luz.",
    width: 4,
    depth: 4,
    cells: [
      { x: 1, y: 1, z: 1 },
      { x: 2, y: 1, z: 1 },
      { x: 2, y: 2, z: 1, lamp: true },
    ],
    start: { x: 1, y: 1, dir: 0 },
    allowed: ["fwd", "left", "right", "light"],
    slots: { main: 8, p1: 0, p2: 0 },
  }),
  L({
    id: "c03",
    name: "Tres lámparas",
    hint: "Recorre el pasillo y enciende cada marca. El orden no importa.",
    width: 5,
    depth: 3,
    cells: [
      { x: 0, y: 1, z: 1, lamp: true },
      { x: 1, y: 1, z: 1 },
      { x: 2, y: 1, z: 1, lamp: true },
      { x: 3, y: 1, z: 1 },
      { x: 4, y: 1, z: 1, lamp: true },
    ],
    start: { x: 0, y: 1, dir: 0 },
    allowed: ["fwd", "left", "right", "light"],
    slots: { main: 12, p1: 0, p2: 0 },
  }),
  L({
    id: "c04",
    name: "Un escalón",
    hint: "Avanzar no sube. Usa Saltar para cambiar un nivel de altura.",
    width: 4,
    depth: 3,
    cells: [
      { x: 0, y: 1, z: 1 },
      { x: 1, y: 1, z: 2, lamp: true },
    ],
    start: { x: 0, y: 1, dir: 0 },
    allowed: ["fwd", "jump", "light"],
    slots: { main: 6, p1: 0, p2: 0 },
  }),
  L({
    id: "c05",
    name: "Escalera",
    hint: "Sube de uno en uno. Saltar también sirve para bajar.",
    width: 5,
    depth: 3,
    cells: [
      { x: 0, y: 1, z: 1 },
      { x: 1, y: 1, z: 2 },
      { x: 2, y: 1, z: 3 },
      { x: 3, y: 1, z: 2 },
      { x: 4, y: 1, z: 1, lamp: true },
    ],
    start: { x: 0, y: 1, dir: 0 },
    allowed: ["fwd", "jump", "light"],
    slots: { main: 10, p1: 0, p2: 0 },
  }),
  L({
    id: "c06",
    name: "Patio cuadrado",
    hint: "Da la vuelta al patio encendiendo las cuatro esquinas.",
    width: 4,
    depth: 4,
    cells: [
      { x: 0, y: 0, z: 1, lamp: true },
      { x: 1, y: 0, z: 1 },
      { x: 2, y: 0, z: 1 },
      { x: 3, y: 0, z: 1, lamp: true },
      { x: 3, y: 1, z: 1 },
      { x: 3, y: 2, z: 1 },
      { x: 3, y: 3, z: 1, lamp: true },
      { x: 2, y: 3, z: 1 },
      { x: 1, y: 3, z: 1 },
      { x: 0, y: 3, z: 1, lamp: true },
      { x: 0, y: 2, z: 1 },
      { x: 0, y: 1, z: 1 },
    ],
    start: { x: 0, y: 0, dir: 0 },
    allowed: ["fwd", "left", "right", "light"],
    slots: { main: 16, p1: 0, p2: 0 },
  }),
  L({
    id: "c07",
    name: "Repite con P1",
    hint: "El patrón avanzar-luz-avanzar se repite. Mételo en el procedimiento 1.",
    width: 6,
    depth: 3,
    cells: [
      { x: 0, y: 1, z: 1 },
      { x: 1, y: 1, z: 1, lamp: true },
      { x: 2, y: 1, z: 1 },
      { x: 3, y: 1, z: 1, lamp: true },
      { x: 4, y: 1, z: 1 },
      { x: 5, y: 1, z: 1, lamp: true },
    ],
    start: { x: 0, y: 1, dir: 0 },
    allowed: ["fwd", "light", "p1"],
    slots: { main: 4, p1: 4, p2: 0 },
  }),
  L({
    id: "c08",
    name: "Dos procedimientos",
    hint: "P1 puede ser “avanzar y encender”. P2 puede ser “girar y avanzar”.",
    width: 4,
    depth: 4,
    cells: [
      { x: 0, y: 0, z: 1, lamp: true },
      { x: 1, y: 0, z: 1 },
      { x: 2, y: 0, z: 1, lamp: true },
      { x: 2, y: 1, z: 1 },
      { x: 2, y: 2, z: 1, lamp: true },
    ],
    start: { x: 0, y: 0, dir: 0 },
    allowed: ["fwd", "right", "light", "p1", "p2"],
    slots: { main: 6, p1: 4, p2: 4 },
  }),
  L({
    id: "c09",
    name: "Torre y foso",
    hint: "Salta al bloque alto, enciende, y salta de nuevo para bajar.",
    width: 5,
    depth: 4,
    cells: [
      { x: 0, y: 1, z: 1 },
      { x: 1, y: 1, z: 2 },
      { x: 2, y: 1, z: 3, lamp: true },
      { x: 3, y: 1, z: 2 },
      { x: 4, y: 1, z: 1, lamp: true },
      { x: 2, y: 2, z: 2 },
      { x: 2, y: 0, z: 2 },
    ],
    start: { x: 0, y: 1, dir: 0 },
    allowed: ["fwd", "left", "right", "jump", "light"],
    slots: { main: 14, p1: 8, p2: 0 },
  }),
  L({
    id: "c10",
    name: "Zigzag",
    hint: "Un mismo giro + avance puede reutilizarse si lo guardas en un procedimiento.",
    width: 5,
    depth: 5,
    cells: [
      { x: 0, y: 0, z: 1, lamp: true },
      { x: 0, y: 1, z: 1 },
      { x: 1, y: 1, z: 1, lamp: true },
      { x: 1, y: 2, z: 1 },
      { x: 2, y: 2, z: 1, lamp: true },
      { x: 2, y: 3, z: 1 },
      { x: 3, y: 3, z: 1, lamp: true },
      { x: 3, y: 4, z: 1 },
      { x: 4, y: 4, z: 1, lamp: true },
    ],
    start: { x: 0, y: 0, dir: 1 },
    allowed: ["fwd", "left", "right", "light", "p1"],
    slots: { main: 8, p1: 6, p2: 0 },
  }),
  L({
    id: "c11",
    name: "Ciudadela",
    hint: "Combina saltos y giros. Las lámparas están a distinta altura.",
    width: 5,
    depth: 5,
    cells: [
      { x: 0, y: 2, z: 1 },
      { x: 1, y: 2, z: 2 },
      { x: 2, y: 2, z: 3, lamp: true },
      { x: 2, y: 1, z: 2 },
      { x: 2, y: 0, z: 1, lamp: true },
      { x: 2, y: 3, z: 2 },
      { x: 2, y: 4, z: 1, lamp: true },
      { x: 3, y: 2, z: 2 },
      { x: 4, y: 2, z: 1, lamp: true },
    ],
    start: { x: 0, y: 2, dir: 0 },
    allowed: ALL,
    slots: { main: 16, p1: 8, p2: 8 },
  }),
  L({
    id: "c12",
    name: "Núcleo",
    hint: "Nivel final: recorre la plataforma, sube al núcleo y enciende todo.",
    width: 6,
    depth: 6,
    cells: [
      { x: 0, y: 0, z: 1, lamp: true },
      { x: 1, y: 0, z: 1 },
      { x: 2, y: 0, z: 1 },
      { x: 3, y: 0, z: 1 },
      { x: 4, y: 0, z: 1 },
      { x: 5, y: 0, z: 1, lamp: true },
      { x: 5, y: 1, z: 1 },
      { x: 5, y: 2, z: 1 },
      { x: 5, y: 3, z: 1 },
      { x: 5, y: 4, z: 1 },
      { x: 5, y: 5, z: 1, lamp: true },
      { x: 4, y: 5, z: 1 },
      { x: 3, y: 5, z: 1 },
      { x: 2, y: 5, z: 1 },
      { x: 1, y: 5, z: 1 },
      { x: 0, y: 5, z: 1, lamp: true },
      { x: 0, y: 4, z: 1 },
      { x: 0, y: 3, z: 1 },
      { x: 0, y: 2, z: 1 },
      { x: 0, y: 1, z: 1 },
      { x: 1, y: 2, z: 2 },
      { x: 2, y: 1, z: 2 },
      { x: 3, y: 2, z: 2 },
      { x: 2, y: 3, z: 2 },
      { x: 2, y: 2, z: 3, lamp: true },
      { x: 3, y: 3, z: 2, lamp: true },
    ],
    start: { x: 0, y: 0, dir: 0 },
    allowed: ALL,
    slots: { main: 18, p1: 10, p2: 10 },
  }),
];

export function blankLevel() {
  return {
    id: `custom-${Date.now()}`,
    name: "Nivel sin título",
    hint: "Describe el objetivo para quien lo juegue.",
    width: 6,
    depth: 6,
    cells: [
      { x: 1, y: 2, z: 1 },
      { x: 2, y: 2, z: 1 },
      { x: 3, y: 2, z: 1, lamp: true },
    ],
    start: { x: 1, y: 2, dir: 0 },
    allowed: ALL,
    slots: { main: 12, p1: 8, p2: 8 },
  };
}
